### ISSUE TITLE
Working on my windows but fail in ubuntu 22.4 with python 3.10

### ISSUE THREAD

**Issue by mdatiqmazumder** [HanaokaYuzu/Gemini-API#4]
Traceback (most recent call last):
  File "/www/gemeni/t.py", line 2, in <module>
    from gemini import GeminiClient
  File "/www/gemeni/gemini.py", line 2, in <module>
    from gemini import GeminiClient
ImportError: cannot import name 'GeminiClient' from partially initialized module 'gemini' (most likely due to a circular import) (/www/gemeni/gemini.py)

**Comment by HanaokaYuzu** [comment]
The problem is your script and its path are named as "gemini", which is identical to the package name. Rename your folder and file and then it should work.

**Comment by Sayarkhwab** [comment]
![Screenshot_20240220-062006_Replit](https://github.com/HanaokaYuzu/Gemini-API/assets/125228685/c03b3040-d523-433a-aa46-50e7bc8f275a)
Replit also gave something like that
